name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches_ignore: []

jobs:
  Linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Linting
        run: |
          pip install pre-commit
          pre-commit run --all-files

  Linux:
    runs-on: ubuntu-latest
    needs: Linting
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Nox and Poetry
      run: |
          pip install nox==2019.11.9
          pip install poetry==1.0.0
    - name: Test
      run: |
          nox
